name: agenteek_files_toolset
description: Agenteek file toolset
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.11.5

resolution: workspace

dependencies:
  collection: any
  dartantic_interface: any
  agenteek: any
  agenteek_files: any
  agenteek_mcp: any
  dart_mcp: any
  glob: any
  path: any

dev_dependencies:
  lints: any
  test: any
