name: _
publish_to: none

environment:
  sdk: ^3.11.5

workspace:
  - packages/*
  - packages/toolsets/*

# dependency_overrides:
#   dartantic_ai:
#     path: C:\_Projects\oss\dartantic\packages\dartantic_ai
#   dartantic_interface:
#     path: C:\_Projects\oss\dartantic\packages\dartantic_interface
