name: agenteek_memory_toolset
description: Agenteek memory toolset.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.11.5

resolution: workspace

# Add regular dependencies here.
dependencies:
  agenteek: any
  agenteek_mcp: any
  dart_mcp: any

dev_dependencies:
  lints: any
  test: any
