name: agenteek_team
description: Agenteek Team of Agents
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.11.5

resolution: workspace

dependencies:
  better_future: ^2.0.3
  dart_mcp: any
  meta: any
  yaml: any
  glob: any
  path: any
  logging: any
  agenteek: any
  agenteek_files: any
  agenteek_mcp_toolset: any
  agenteek_memory_toolset: any
  agenteek_files_toolset: any
  agenteek_dart_toolset: any
  agenteek_tickets_toolset: any

dev_dependencies:
  lints: any
  test: any
