import 'dart:io';

import 'package:agenteek/agenteek.dart';
import 'package:agenteek_containers/agenteek_containers.dart';
import 'package:agenteek_files/agenteek_files_io.dart';

import '../dart_toolset.dart';
import '_json_arguments.dart';

// run
Tool<Json> runTool(DartToolSet toolSet) => Tool(
  name: toolSet.buildToolName('run'),
  description: toolSet.buildDescription('Runs a Dart script'),
  inputSchema: RunArgs.schema,
  onCall: (args) => _run(toolSet, RunArgs(args)),
);

Future<ToolSuccess<Json>> _run(DartToolSet toolSet, RunArgs args) async {
  final script = await File(args.scriptPath).check(toolSet.root);
  if (!await script.exists()) {
    throw 'Not found: ${script.getLocalPath(toolSet.root)}';
  }

  // check if podman is available
  if (!await toolSet.checkPodman()) {
    throw 'Podman is not available. Please install Podman and try again.';
  }

  // Script code was generated by AI: we'll execute it in a sandbox.
  final podman = PodmanContainer(image: 'dart:stable');
  Json result;
  try {
    await podman.start();
    await podman.rmdir('/sandbox');
    await podman.cpdir(Directory(toolSet.root), '/sandbox');
    await podman.run('dart pub get', workingDir: '/sandbox');
    result = await podman.run(
      'dart run ${script.getLocalPath(toolSet.root).replaceAll('\\', '/')}',
      workingDir: '/sandbox',
    );
  } finally {
    await podman.stop();
  }

  return ToolSuccess(result);
}
