import 'dart:io';

import 'package:agenteek/agenteek.dart';
import 'package:agenteek_containers/agenteek_containers.dart';
import 'package:agenteek_files/agenteek_files_io.dart';

import '../dart_toolset.dart';

// run
Tool runTool(DartToolSet toolSet) => Tool(
  name: toolSet.buildToolName('run'),
  description: toolSet.buildDescription('Runs a Dart script'),
  inputSchema: _inputSchema,
  onCall: (args) => _run(toolSet, args),
);

Future<ToolSuccess<Json>> _run(DartToolSet toolSet, Json args) async {
  var path = args.getString('path');
  if (path.startsWith('/')) path = path.substring(1);

  final script = await File(path).check(toolSet.root);
  if (!await script.exists()) {
    throw 'Not found: ${script.getLocalPath(toolSet.root)}';
  }

  // check if podman is available
  if (!await toolSet.checkPodman()) {
    throw 'Podman is not available. Please install Podman and try again.';
  }

  // Script code was generated by AI: we'll execute it in a sandbox.
  final podman = PodmanContainer(image: 'dart:stable');
  Json result;
  try {
    await podman.start();
    await podman.rmdir('/sandbox');
    await podman.cpdir(Directory(toolSet.root), '/sandbox');
    await podman.run('dart pub get', workingDir: '/sandbox');
    result = await podman.run(
      'dart run ${script.getLocalPath(toolSet.root).replaceAll('\\', '/')}',
      workingDir: '/sandbox',
    );
  } finally {
    await podman.stop();
  }

  return ToolSuccess(result);
}

final _inputSchema = Z.object(
  properties: {'path': Z.string(description: 'The path to the Dart script.')},
  required: ['path'],
);
