name: agenteek
description: A powerful and flexible toolkit for building agentic AI applications with Dart.
version: 1.0.0
repository: https://github.com/d-markey/agenteek
funding:
  - https://github.com/sponsors/d-markey

environment:
  sdk: ^3.11.5

resolution: workspace

dependencies:
  async: ^2.13.1
  collection: ^1.19.1
  cancelation_token: ^1.1.0
  dartantic_ai: ^3.4.0
  path: ^1.9.1
  http: ^1.6.0
  dart_mcp: ^0.5.0
  stream_channel: ^2.1.4
  glob: ^2.1.3
  yaml: ^3.1.3
  web: ^1.1.1
  meta: ^1.17.0
  logging: ^1.3.0

dev_dependencies:
  lints:
  test:
