name: agenteek
description: A powerful and flexible toolkit for building agentic AI applications with Dart.
version: 1.0.0
repository: https://github.com/d-markey/agenteek
funding:
  - https://github.com/sponsors/d-markey

environment:
  sdk: ^3.11.5

resolution: workspace

dependencies:
  cancelation_token: ^1.1.0
  dartantic_ai: ^3.4.0
  path: ^1.9.1
  web: ^1.1.1
  logging: ^1.3.0

dev_dependencies:
  lints: any
  test: any
