name: agenteek_tickets_toolset
description: Agenteek tickets toolset
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.0

resolution: workspace

dependencies:
  agenteek: any
  agenteek_mcp: any
  dart_mcp: any
  logging: any

dev_dependencies:
  lints: any
  test: any
