name: agenteek_dart_toolset
description: Agenteek Dart toolset.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.11.5

resolution: workspace

# Add regular dependencies here.
dependencies:
  dartantic_interface:
  agenteek:
  agenteek_containers:
  agenteek_files:
  dart_mcp:
  path:
  meta:

dev_dependencies:
  lints:
  test:
