name: agenteek_container
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.11.0

resolution: workspace

# Add regular dependencies here.
dependencies:
  agenteek:

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
