name: agenteek_web
description: An absolute bare-bones web app.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.11.5

resolution: workspace

# Add regular dependencies here.
dependencies:
  better_future: ^2.0.3
  web: any
  dart_mcp: any
  dartantic_interface: any
  agenteek: any
  agenteek_mcp_toolset: any
  markdown: any
  cancelation_token: any
  pdf: any

dev_dependencies:
  cors_enabler: any
  build_runner: any
  build_web_compilers: any
  preload: any
  lints: any
