name: agenteek_containers
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.11.5

resolution: workspace

# Add regular dependencies here.
dependencies:
  agenteek: any
  logging: any

dev_dependencies:
  lints: any
  test: any
